name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest     

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
      
    - name: Install dependencies 1
      run: pip install pytest

    - name: Install dependencies 2
      run: pip install pytest-html

    - name: Install dependencies 3
      run: pip install selenium
      
    - name: Execute tests
      run: |
        cd Exercise2-UI
        pytest --headless True --disable-dev-shm-usage True --html=report.html
      shell: bash 
      
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: Exercise2-UI/report.html
